version: '2.2'

services:
  app:
    image: ghcr.io/anh4n/skyjo:${TAG:-latest}
    container_name: skyjo-calculator
    labels:
      traefik.http.routers.skyjo.rule: "Host(`skyjo.xhttp.de`)"
      traefik.http.routers.skyjo.tls.certresolver: "letsencrypt"
      traefik.http.routers.skyjo.entrypoints: "websecure"
      traefik.http.services.skyjo.loadbalancer.server.port: "80"
    init: true

networks:
  default:
    external:
      name: reverse_proxy